<?xml version="1.0" encoding="utf-8"?><Database Name="QL_QUANAO" Class="ShopQuanAoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PHUONGTRAN\PHUONG;Initial Catalog=QL_QUANAO;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QL_QUANAOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHITIETHD" Member="CHITIETHDs">
    <Type Name="CHITIETHD">
      <Column Name="MAHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHD" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
      <Association Name="SANPHAM_CHITIETHD" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THONGTINTAIKHOAN" Member="THONGTINTAIKHOANs">
    <Type Name="THONGTINTAIKHOAN">
      <Column Name="TENTK" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGSINH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="GTINH" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="NGTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="DCHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="TAIKHOAN_THONGTINTAIKHOAN" Member="TAIKHOAN" ThisKey="TENTK" OtherKey="TENTK" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DOITRA" Member="DOITRAs">
    <Type Name="DOITRA">
      <Column Name="MAHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTK" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NGDOI" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LYDO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="HOADON_DOITRA" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" />
      <Association Name="SANPHAM_DOITRA" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
      <Association Name="TAIKHOAN_DOITRA" Member="TAIKHOAN" ThisKey="TENTK" OtherKey="TENTK" Type="TAIKHOAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NGTAO" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="THANHTOAN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MAKM" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="HOADON_CHITIETHD" Member="CHITIETHDs" ThisKey="MAHD" OtherKey="MAHD" Type="CHITIETHD" />
      <Association Name="HOADON_DOITRA" Member="DOITRAs" ThisKey="MAHD" OtherKey="MAHD" Type="DOITRA" />
      <Association Name="KHUYENMAI_HOADON" Member="KHUYENMAI" ThisKey="MAKM" OtherKey="MAKM" Type="KHUYENMAI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHUYENMAI" Member="KHUYENMAIs">
    <Type Name="KHUYENMAI">
      <Column Name="MAKM" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKM" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="GIAMGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="KHUYENMAI_HOADON" Member="HOADONs" ThisKey="MAKM" OtherKey="MAKM" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.LOAISP" Member="LOAISPs">
    <Type Name="LOAISP">
      <Column Name="MALSP" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LOAISP_SANPHAM" Member="SANPHAMs" ThisKey="MALSP" OtherKey="MALSP" Type="SANPHAM" />
    </Type>
  </Table>
  <Table Name="dbo.NCC" Member="NCCs">
    <Type Name="NCC">
      <Column Name="MANCC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NCC_NHAPHANG" Member="NHAPHANGs" ThisKey="MANCC" OtherKey="MANCC" Type="NHAPHANG" />
    </Type>
  </Table>
  <Table Name="dbo.NHAPHANG" Member="NHAPHANGs">
    <Type Name="NHAPHANG">
      <Column Name="MANHAP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MASP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MANCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGNHAP" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DONGIANHAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NCC_NHAPHANG" Member="NCC" ThisKey="MANCC" OtherKey="MANCC" Type="NCC" IsForeignKey="true" />
      <Association Name="SANPHAM_NHAPHANG" Member="SANPHAM" ThisKey="MASP" OtherKey="MASP" Type="SANPHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QUYEN" Member="QUYENs">
    <Type Name="QUYEN">
      <Column Name="MAQUYEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENQUYEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QUYEN_TAIKHOAN" Member="TAIKHOANs" ThisKey="MAQUYEN" OtherKey="MAQUYEN" Type="TAIKHOAN" />
    </Type>
  </Table>
  <Table Name="dbo.SANPHAM" Member="SANPHAMs">
    <Type Name="SANPHAM">
      <Column Name="MASP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENSP" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SIZE" Type="System.String" DbType="VarChar(3)" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DONGIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HINHANH" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MALSP" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Association Name="SANPHAM_CHITIETHD" Member="CHITIETHDs" ThisKey="MASP" OtherKey="MASP" Type="CHITIETHD" />
      <Association Name="SANPHAM_DOITRA" Member="DOITRAs" ThisKey="MASP" OtherKey="MASP" Type="DOITRA" />
      <Association Name="SANPHAM_NHAPHANG" Member="NHAPHANGs" ThisKey="MASP" OtherKey="MASP" Type="NHAPHANG" />
      <Association Name="LOAISP_SANPHAM" Member="LOAISP" ThisKey="MALSP" OtherKey="MALSP" Type="LOAISP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAIKHOAN" Member="TAIKHOANs">
    <Type Name="TAIKHOAN">
      <Column Name="TENTK" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="MAQUYEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="TAIKHOAN_THONGTINTAIKHOAN" Member="THONGTINTAIKHOAN" ThisKey="TENTK" OtherKey="TENTK" Type="THONGTINTAIKHOAN" Cardinality="One" />
      <Association Name="TAIKHOAN_DOITRA" Member="DOITRAs" ThisKey="TENTK" OtherKey="TENTK" Type="DOITRA" />
      <Association Name="QUYEN_TAIKHOAN" Member="QUYEN" ThisKey="MAQUYEN" OtherKey="MAQUYEN" Type="QUYEN" IsForeignKey="true" />
    </Type>
  </Table>
</Database>